-- MCP 服务器配置表
CREATE TABLE IF NOT EXISTS mcp_server (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bid VARCHAR(64),
    tenant_id BIGINT NOT NULL,
    created_by BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN DEFAULT FALSE NOT NULL,

    -- 服务器基本信息
    server_code VARCHAR(128) NOT NULL,
    server_name VARCHAR(255) NOT NULL,
    server_type VARCHAR(64) NOT NULL,  -- stdio, http, sse

    -- 连接配置
    server_url VARCHAR(512),  -- http/sse 类型
    command VARCHAR(512),     -- stdio 类型
    args_json TEXT,           -- 命令参数
    env_json TEXT,            -- 环境变量

    -- 状态信息
    status VARCHAR(64) DEFAULT 'active',  -- active, inactive, error
    last_error TEXT,
    tool_count INTEGER DEFAULT 0,

    -- 唯一约束
    CONSTRAINT uk_mcp_server_code UNIQUE (tenant_id, server_code)
);

-- 索引
CREATE INDEX IF NOT EXISTS idx_mcp_server_tenant ON mcp_server(tenant_id);
CREATE INDEX IF NOT EXISTS idx_mcp_server_status ON mcp_server(status);
