-- 人格表
CREATE TABLE IF NOT EXISTS personality (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bid VARCHAR(64),
    tenant_id BIGINT NOT NULL,
    created_by BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN DEFAULT FALSE NOT NULL,

    -- 人格基本信息
    personality_code VARCHAR(128) NOT NULL,
    personality_name VARCHAR(255) NOT NULL,
    description TEXT,
    content TEXT NOT NULL,  -- Markdown 格式的人格内容

    -- 人格类型
    personality_type VARCHAR(64) DEFAULT 'custom',  -- professional, friendly, expert, creative, custom

    -- 关联信息
    agent_id BIGINT,  -- 适用的 Agent ID（空表示通用）
    created_by_user_id BIGINT,

    -- 分享和统计
    is_public BOOLEAN DEFAULT FALSE,
    usage_count INTEGER DEFAULT 0,
    rating INTEGER DEFAULT 0,

    -- 标签
    tags_json TEXT,

    -- 状态
    status VARCHAR(64) DEFAULT 'active',  -- active, archived

    -- 唯一约束
    CONSTRAINT uk_personality_code UNIQUE (tenant_id, personality_code)
);

-- 索引
CREATE INDEX IF NOT EXISTS idx_personality_tenant ON personality(tenant_id);
CREATE INDEX IF NOT EXISTS idx_personality_agent ON personality(agent_id);
CREATE INDEX IF NOT EXISTS idx_personality_type ON personality(personality_type);
CREATE INDEX IF NOT EXISTS idx_personality_public ON personality(is_public);
CREATE INDEX IF NOT EXISTS idx_personality_usage ON personality(usage_count DESC, rating DESC);

-- 插入示例人格
INSERT INTO personality (bid, tenant_id, personality_code, personality_name, description, content, personality_type, is_public, status)
VALUES
('PROF-ASSISTANT', 100, 'professional-assistant', 'Professional Assistant',
 'A professional and efficient AI assistant',
 '# Professional Assistant

You are a professional AI assistant focused on delivering high-quality, efficient, and accurate responses.

## Communication Style
- Be concise and direct
- Use professional language
- Focus on facts and data
- Provide actionable recommendations

## Behavior
- Prioritize accuracy over speed
- Ask clarifying questions when needed
- Provide structured responses
- Cite sources when applicable',
 'professional', true, 'active'),

('FRIENDLY-HELPER', 100, 'friendly-helper', 'Friendly Helper',
 'A friendly and approachable AI companion',
 '# Friendly Helper

You are a friendly and approachable AI companion who makes interactions enjoyable.

## Communication Style
- Use casual, friendly language
- Include occasional humor
- Be encouraging and supportive
- Use emojis occasionally 😊

## Behavior
- Make conversations enjoyable
- Be patient and understanding
- Offer help proactively
- Celebrate user successes',
 'friendly', true, 'active')
ON CONFLICT (tenant_id, personality_code) DO NOTHING;
