-- 定时任务表
CREATE TABLE IF NOT EXISTS scheduled_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bid VARCHAR(64),
    tenant_id BIGINT NOT NULL,
    created_by BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN DEFAULT FALSE NOT NULL,

    -- 任务基本信息
    task_code VARCHAR(128) NOT NULL,
    task_name VARCHAR(255) NOT NULL,
    description TEXT,

    -- 调度配置
    cron_expression VARCHAR(128),  -- Cron 表达式
    natural_language TEXT,          -- 自然语言描述

    -- 任务类型
    task_type VARCHAR(64) DEFAULT 'custom',  -- agent_task, workflow, notification, custom

    -- 关联信息
    agent_id BIGINT,  -- 关联的 Agent ID

    -- 任务配置
    task_config TEXT,           -- 任务配置（JSON）
    delivery_targets TEXT,      -- 投递目标（JSON数组）

    -- 创建者
    created_by_user_id BIGINT,

    -- 执行统计
    last_execution_time TIMESTAMP WITH TIME ZONE,
    next_execution_time TIMESTAMP WITH TIME ZONE,
    execution_count INTEGER DEFAULT 0,
    success_count INTEGER DEFAULT 0,
    failure_count INTEGER DEFAULT 0,

    -- 状态
    is_enabled BOOLEAN DEFAULT TRUE,
    status VARCHAR(64) DEFAULT 'active',  -- active, paused, error

    -- 唯一约束
    CONSTRAINT uk_scheduled_task_code UNIQUE (tenant_id, task_code)
);

-- 索引
CREATE INDEX IF NOT EXISTS idx_scheduled_task_tenant ON scheduled_task(tenant_id);
CREATE INDEX IF NOT EXISTS idx_scheduled_task_agent ON scheduled_task(agent_id);
CREATE INDEX IF NOT EXISTS idx_scheduled_task_user ON scheduled_task(created_by_user_id);
CREATE INDEX IF NOT EXISTS idx_scheduled_task_enabled ON scheduled_task(is_enabled);
CREATE INDEX IF NOT EXISTS idx_scheduled_task_next_execution ON scheduled_task(next_execution_time);
CREATE INDEX IF NOT EXISTS idx_scheduled_task_status ON scheduled_task(status);

-- 插入示例定时任务
INSERT INTO scheduled_task (bid, tenant_id, task_code, task_name, description, cron_expression, natural_language, task_type, is_enabled, status)
VALUES
('DAILY-REPORT', 100, 'daily-morning-report', 'Daily Morning Report',
 'Generate a daily report every morning at 9 AM',
 '0 0 9 * * ?', '每天早上9点生成日报', 'agent_task', true, 'active'),

('WEEKLY-SUMMARY', 100, 'weekly-summary', 'Weekly Summary',
 'Generate a weekly summary every Monday at 10 AM',
 '0 0 10 ? * MON', '每周一上午10点生成周报', 'agent_task', true, 'active')
ON CONFLICT (tenant_id, task_code) DO NOTHING;
